//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Author
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Author()
    {
        this.Books = new HashSet<Book>();
    }

    public int AuthorKey { get; set; }
    public string AuthorName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class Book
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {
        this.Reviews = new HashSet<Review>();
        this.Authors = new HashSet<Author>();
        this.Categories = new HashSet<Category>();
    }

    public int BookKey { get; set; }
    public string BookTitle { get; set; }
    public System.DateTime BookEntryDate { get; set; }
    public string BookISBN { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Review> Reviews { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Author> Authors { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Category> Categories { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Books = new HashSet<Book>();
    }

    public int CategoryKey { get; set; }
    public string CategoryName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class CheckinLog
{
    public int CheckInLogKey { get; set; }
    public int ReviewerKey { get; set; }
    public System.DateTime CheckinDateTime { get; set; }

    public virtual Reviewer Reviewer { get; set; }
}

public partial class Review
{
    public int ReviewKey { get; set; }
    public int BookKey { get; set; }
    public int ReviewerKey { get; set; }
    public System.DateTime ReviewDate { get; set; }
    public string ReviewTitle { get; set; }
    public int ReviewRating { get; set; }
    public string ReviewText { get; set; }

    public virtual Book Book { get; set; }
    public virtual Reviewer Reviewer { get; set; }
}

public partial class Reviewer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Reviewer()
    {
        this.CheckinLogs = new HashSet<CheckinLog>();
        this.Reviews = new HashSet<Review>();
    }

    public int ReviewerKey { get; set; }
    public string ReviewerUserName { get; set; }
    public string ReviewerFirstName { get; set; }
    public string ReviewerLastName { get; set; }
    public string ReviewerEmail { get; set; }
    public int ReviewerKeyCode { get; set; }
    public string ReviewPlainPassword { get; set; }
    public byte[] ReviewerHashedPass { get; set; }
    public Nullable<System.DateTime> ReviewerDateEntered { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CheckinLog> CheckinLogs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Review> Reviews { get; set; }
}
